test: &default
  client_id: <%= ENV["PAYPAL_CLIENT_ID"] %>
  client_secret: <%= ENV["PAYPAL_CLIENT_SECRET"] %>
  mode: <%= ENV["PAYPAL_MODE"] %>

development:
  <<: *default

production:
  <<: *default
